### ISSUE TITLE
Can you just show me a list of malicious urls, the data displayed on https://www.azsecure-data.org/phishing-websites.html is too huge.

### ISSUE THREAD

**Issue by fight-think** [mcintirecba/phishmonger#1]

**Comment by davedgd** [comment]
Unfortunately even an index of the files is massive since the database is so large. Two options that might work:

- use the slightly older but more focused Targeted Brands data set, which includes URLs and other relevant metadata
- use the index files zip that was recently added on AZSecure-data.org, since it similarly focuses on metadata such as URLs

**Comment by fight-think** [comment]
Thank you so much. I get it, I will try small urls dataset list upon website.------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;David&amp;nbsp;Dobolyi&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月18日(星期四) 凌晨0:44
收件人:&nbsp;&quot;mcintirecba/phishmonger&quot;<phishmonger@noreply.github.com&gt;;
抄送:&nbsp;&quot;little_jia_like_reading&quot;<1297518605@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mcintirecba/phishmonger] Can you just show me a list of malicious urls, the data displayed on https://www.azsecure-data.org/phishing-websites.html is too huge. (#1)
